### PR TITLE
added uncertainty quantitification

### PR DESCRIPTION
**Pull request by pyatsysh**
1. Added bootstrapping routine; changed signature of train_dmd to all optional choice of constraints on eigenval
2. Reflected new capabilities in readme, where added two figures

### CODE REVIEW

**Review by LydiaFrance — APPROVED** [review]
Seems to work except one change was required. In demo2 notebook still had `rank = rank` which should be changed to `svd_rank = rank` for `train_dmd()`

**Comment by ots22** [comment]
Can we merge this yet?

**Comment by louisavz** [comment]
pyDMD now has bagging capability. Will default to using the builtin function.

**Comment by dsj976** [comment]
For now, we will be using the built-in capability in PyDMD. If it doesn't work there (for whatever reason), we can open a PR/issue in the PyDMD repo

**Pull request closed without merging**
